version: 2

sources:
  my_data_source: # Ett logiskt namn för din source (du väljer detta namn)
    database: primeval-rune-447712-f5 # Ditt GCP-projekt-ID
    schema: futurewaterlevel # Ditt BigQuery dataset
    tables:
      - name: users # Det *exakta* namnet på tabellen i BigQuery
        description: "Användardata" # Valfri beskrivning
      - name: raw_logs # Det *exakta* namnet på tabellen i BigQuery
        description: "Rå loggdata" # Valfri beskrivning
      - name: events # Det *exakta* namnet på tabellen i BigQuery
        description: "Händelsedata" # Valfri beskrivning