name: "my_local_dbt_and_gcp_project"
version: "1.0"
profile: "oscar_dunge_gcp"
config-version: 2
model-paths: ["models"]
macro-paths: ["macros"]
models:
      +materialized: view  # Staging models are views
