version: 2  # Ensure version is a number, not a string

sources:  # Indent this line
  main:  # Indent this line
    database: primeval-rune-447712-f5  # Your GCP project ID
    schema: futurewaterlevel
    tables:
      - name: events # The final, renamed table
      - name: staging_csv_data_events_{{ run_started_at.strftime("%Y%m%d") }} # Dynamic staging table



